# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0002_auto_20170308_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
        migrations.AddField(
            model_name='ads',
            name='ad_name',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='client_name',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
