# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0003_auto_20170309_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='source',
            field=models.FileField(upload_to='LocalAdStorage'),
        ),
    ]
