# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0004_auto_20170310_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='local_source',
        ),
    ]
