# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0005_remove_ads_local_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='id',
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
