# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0007_auto_20170313_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_clients',
            field=models.ManyToManyField(blank=True, to='clientManager.clients'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_ads',
            field=models.ManyToManyField(blank=True, to='clientManager.ads'),
        ),
    ]
