# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0008_auto_20170404_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='thumbnail',
            field=models.CharField(default='clientManager/thumbs/flash.png', max_length=128),
            preserve_default=False,
        ),
    ]
