# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0009_ads_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='connectivity',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='cpu_percentages',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='disk_space',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='latency',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='playing',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='ram_percentages',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='temperature',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
