# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0010_auto_20170408_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('days', models.CharField(max_length=64)),
                ('interval_one', models.CharField(max_length=12)),
                ('interval_two', models.CharField(max_length=12)),
                ('interval_three', models.CharField(max_length=12)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientManager.ads')),
            ],
        ),
        migrations.CreateModel(
            name='client_health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('disk_space', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('temperature', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('latency', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('playing', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('cpu_percentages', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ram_percentages', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('time', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='cpu_percentages',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='disk_space',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='playing',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='ram_percentages',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='time',
        ),
        migrations.AddField(
            model_name='client_health',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientManager.clients'),
        ),
    ]
