# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0011_auto_20170421_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_health',
            name='id',
        ),
        migrations.AlterField(
            model_name='client_health',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientManager.clients'),
        ),
    ]
